### PR TITLE
SUGGESTION: idea for ampy.json to reduce command line parameters

### PR DESCRIPTION
**Pull request by ahaeberle**
Hi Adafruit-Team,

what do you think about an environ(mental) free usage of ampy but with a json config (I also could see a toml/ini/yaml file here).

The idea would be, that the ampy.json could live in the project folder and used for improved commands on get, put and ls.

This also helps the poor developer to remember this settings from half some months ago (hence they are documented and checked in)

Please feel free to comment on my python style if you see anything disgusting.

### CODE REVIEW

**Comment by ladyada** [comment]
Hiya! Thank you for your contribution. We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.

**Comment by devxpy** [comment]
Thanks, this looks nice, but I wonder if we actually need this in the project itself. Isn't this better solved as a simple shell function / alias?

I don't see any functionality that this implements, which cannot be otherwise done using simple modifications to your shell config.

**Comment by ahaeberle** [comment]
Are you woring on linux or mac?
How would you implement this in a porable way especially on windows?
 
Von: Dev Aggarwal [mailto:notifications@github.com] 
Gesendet: Mittwoch, 23. Januar 2019 00:00
An: pycampers/ampy <ampy@noreply.github.com>
Cc: ahaeberle <andreas.haeberle@vipco.de>; Author <author@noreply.github.com>
Betreff: Re: [pycampers/ampy] SUGGESTION: idea for ampy.json to reduce command line parameters (#73)
 
Thanks, this looks nice, but I wonder if we actually need this in the project itself. Isn't this better solved as a simple shell function / alias?
I don't see any functionality that this implements, which cannot be otherwise done using simple modifications to your shell config.

**Comment by devxpy** [comment]
The `.ampy` file does not work on windows?

**Pull request closed without merging**
